/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BasicModal: typeof import('./../src/components/Modal/src/BasicModal.vue')['default']
    NutActionSheet: typeof import('@nutui/nutui')['ActionSheet']
    NutAvatar: typeof import('@nutui/nutui')['Avatar']
    NutButton: typeof import('@nutui/nutui')['Button']
    NutCard: typeof import('@nutui/nutui')['Card']
    NutCell: typeof import('@nutui/nutui')['Cell']
    NutCellGroup: typeof import('@nutui/nutui')['CellGroup']
    NutCol: typeof import('@nutui/nutui')['Col']
    NutDatePicker: typeof import('@nutui/nutui')['DatePicker']
    NutDivider: typeof import('@nutui/nutui')['Divider']
    NutDrag: typeof import('@nutui/nutui')['Drag']
    NutEllipsis: typeof import('@nutui/nutui')['Ellipsis']
    NutEmpty: typeof import('@nutui/nutui')['Empty']
    NutFixedNav: typeof import('@nutui/nutui')['FixedNav']
    NutForm: typeof import('@nutui/nutui')['Form']
    NutFormItem: typeof import('@nutui/nutui')['FormItem']
    NutImage: typeof import('@nutui/nutui')['Image']
    NutIndicator: typeof import('@nutui/nutui')['Indicator']
    NutInfiniteLoading: typeof import('@nutui/nutui')['InfiniteLoading']
    NutInput: typeof import('@nutui/nutui')['Input']
    NutInputNumber: typeof import('@nutui/nutui')['InputNumber']
    NutMenu: typeof import('@nutui/nutui')['Menu']
    NutMenuItem: typeof import('@nutui/nutui')['MenuItem']
    NutPopup: typeof import('@nutui/nutui')['Popup']
    NutProgress: typeof import('@nutui/nutui')['Progress']
    NutRadio: typeof import('@nutui/nutui')['Radio']
    NutRadioGroup: typeof import('@nutui/nutui')['RadioGroup']
    NutRow: typeof import('@nutui/nutui')['Row']
    NutSkeleton: typeof import('@nutui/nutui')['Skeleton']
    NutSpace: typeof import('@nutui/nutui')['Space']
    NutSwipe: typeof import('@nutui/nutui')['Swipe']
    NutTabbar: typeof import('@nutui/nutui')['Tabbar']
    NutTabbarItem: typeof import('@nutui/nutui')['TabbarItem']
    NutTextarea: typeof import('@nutui/nutui')['Textarea']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanNavBar: typeof import('vant/es')['NavBar']
  }
}
